# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z5ti9GU64LwPSh4nfh3tdZkrp1eLvfhW
"""

with open("app.py", "w") as f:
    f.write('import streamlit as st\n')
    f.write('import random\n')
    f.write('import time\n')
    f.write('st.set_page_config(page_title="PromoYA", layout="centered")\n')
    f.write('st.markdown("""<style>body {background-color: #e0f2ff;}</style>""", unsafe_allow_html=True)\n')
    f.write('st.title("📍 PromoYA: Promociones cerca de ti")\n\n')

    f.write('# --- Base de datos ficticia ---\n')
    f.write('promos = [\n')
    f.write('    {"nombre": "Pizza Pepperoni", "categoria": "Comida", "precio": 120, "negocio": "Pizzería Bella", "distancia": "1.5 km", "img": "https://images.unsplash.com/photo-1601924928198-6e7b9dcd8379"},\n')
    f.write('    {"nombre": "Vestido de verano", "categoria": "Ropa", "precio": 450, "negocio": "Moda Linda", "distancia": "0.8 km", "img": "https://images.unsplash.com/photo-1523275335684-37898b6baf30"},\n')
    f.write('    {"nombre": "Smartphone", "categoria": "Tecnología", "precio": 3500, "negocio": "Tecno Outlet", "distancia": "2.1 km", "img": "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9"},\n')
    f.write('    {"nombre": "Pan artesanal", "categoria": "Comida", "precio": 60, "negocio": "Buen Sabor", "distancia": "0.5 km", "img": "https://images.unsplash.com/photo-1585238341986-0c7d61c6b4bb"}\n')
    f.write(']\n\n')

    f.write('# --- Buscar ---\n')
    f.write('query = st.text_input("🔍 Buscar promociones")\n')
    f.write('filtradas = [p for p in promos if query.lower() in p["nombre"].lower() or query.lower() in p["categoria"].lower()]\n\n')

    f.write('# --- Filtros por categoría ---\n')
    f.write('st.markdown("#### Filtrar por categoría:")\n')
    f.write('cols = st.columns(3)\n')
    f.write('cat = st.session_state.get("filtro", "")\n')
    f.write('if cols[0].button("🍔 Comida"): st.session_state.filtro = "Comida"\n')
    f.write('if cols[1].button("👗 Ropa"): st.session_state.filtro = "Ropa"\n')
    f.write('if cols[2].button("📱 Tecnología"): st.session_state.filtro = "Tecnología"\n\n')

    f.write('if "filtro" in st.session_state:\n')
    f.write('    filtradas = [p for p in filtradas if p["categoria"] == st.session_state.filtro]\n\n')

    f.write('# --- Favoritos ---\n')
    f.write('if "favoritos" not in st.session_state:\n')
    f.write('    st.session_state.favoritos = []\n\n')

    f.write('# --- Mostrar promociones ---\n')
    f.write('st.markdown("### 🛍️ Promociones:")\n')
    f.write('for promo in filtradas:\n')
    f.write('    st.image(promo["img"], width=250)\n')
    f.write('    st.markdown(f"**{promo[\'nombre\']} - ${promo[\'precio\']}**")\n')
    f.write('    st.markdown(f"{promo[\'negocio\']} ({promo[\'distancia\']})")\n')
    f.write('    if st.button(f"⭐ Guardar {promo[\'nombre\']}"):\n')
    f.write('        st.session_state.favoritos.append(promo)\n')
    f.write('    st.markdown("---")\n\n')

    f.write('# --- Favoritos guardados ---\n')
    f.write('st.markdown("### ❤️ Mis favoritos")\n')
    f.write('for fav in st.session_state.favoritos:\n')
    f.write('    st.markdown(f"✔️ {fav[\'nombre\']} - ${fav[\'precio\']}")\n\n')

    f.write('# --- Publicar nueva promo ---\n')
    f.write('st.markdown("### ✏️ Publicar tu promoción")\n')
    f.write('with st.form("form_nueva"):\n')
    f.write('    nombre = st.text_input("Nombre del producto")\n')
    f.write('    precio = st.number_input("Precio", min_value=1)\n')
    f.write('    categoria = st.selectbox("Categoría", ["Comida", "Ropa", "Tecnología"])\n')
    f.write('    negocio = st.text_input("Nombre del negocio")\n')
    f.write('    generado = f"¡No te pierdas esta promo de {nombre.lower()} solo por ${precio}! Disponible en {negocio}."\n')
    f.write('    enviado = st.form_submit_button("Publicar")\n')
    f.write('    if enviado:\n')
    f.write('        st.success("🎉 Promoción publicada (simulada)")\n')
    f.write('        st.markdown(f"📣 Texto generado automáticamente: _{generado}_")\n')

!pip install -q streamlit pyngrok

# Importamos librerías necesarias
from pyngrok import ngrok
import threading
import time

# Iniciar streamlit en segundo plano
def start_streamlit():
    !streamlit run app.py

# Ejecutar streamlit en un hilo
thread = threading.Thread(target=start_streamlit)
thread.start()

# Esperar unos segundos a que arranque streamlit
time.sleep(5)

# Conectarse a ngrok
public_url = ngrok.connect(8501)
print(f"✅ Abre esta URL para ver tu app: {public_url}")